<?$this->renderScript('common/user-head.phtml')?>
<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6 col-md-6">
                <h3>Sign in with your account</h3>
                <form role="form" id="signin-form">
                     <div class="form-group"><input id="signin-email" placeholder="E-mail" class="form-control" required="required" type="email"></div>
                     <div class="form-group"><input id="signin-password" placeholder="Password" class="form-control" required="required" type="password"></div>
                     <div class="form-group"><button id="signin-button" type="button" class="btn btn-primary btn-lg">Sign In</button></div>
                </form>
            </div>
            <div class="col-sm-6 col-md-6">
                <h3>Don't have account yet? Sign Up!</h3>
                <form role="form" id="signin-form">
                    <div class="form-group"><input id="signup-email" name="email" placeholder="E-mail" class="form-control" required="required" type="email" data-validation="required email"></div>
                    <div class="form-group"><input id="signup-password" name="password" placeholder="Password" class="form-control" required="required" type="password"></div>
                    <div class="form-group"><input id="signup-password2" name="password2" placeholder="Enter password again" class="form-control" required="required" type="password"></div>
                    <div class="form-group"><button id="signup-button" type="button" class="btn btn-success btn-lg">Sign Up!</button></div>
                </form>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
</div>

<script>
function signup() {
     email = $('#signup-email').val();
     password = $('#signup-password').val();
     password2 = $('#signup-password2').val();
     if (email.length<1) {
          alert('Please enter your E-mail address');
          return;
     }
     if (password.length<1) {
          alert('Please enter password');
          return;
     }
     if (password != password2) {
          alert('The password you entered does not match');
          return;
     }
     p = {};
     p['email'] = email;
     p['password'] = password;
     $.post('/private-car/sign-up?t='+Math.random(), p, function(data) {
          signupDidComplete(data);
     }, 'json')
     .error(function(e) { alert('Error occured while signing up, please retry later.' + e); });
}
function signupDidComplete(data) {
     s = '';
     if (data['status'] == 0) {
          for (var id in data['errors']) {
               if (data['errors'].hasOwnProperty(id)) {
                    s += data['errors'][id] + "\n";
               }
          }
          alert("Error occured: \n" +s);
          return;
     }
     document.location.href="/private-car";
}

function signin() {
     email = $('#signin-email').val();
     password = $('#signin-password').val();
     if (email.length<1) {
          alert('Please enter Email.');
          return;
     }
     if (password.length<1) {
          alert('Please enter password.');
          return;
     }
     p = {};
     p['email'] = email;
     p['password'] = password;
     $.post('/private-car/sign-in?t='+Math.random(), p, function(data) {
          signinDidComplete(data);
     }, 'json')
     .error(function(e) { alert('Failed to signing in, please try again later.' + e); });
}
function signinDidComplete(data) {
     s = '';
     if (data['status'] == 0) {
          s = data['message'];
          alert("Login failed with the following error(s): \n" +s);
          return;
     }
     document.location.href="/private-car";
}

$('#signin-button').on('click', signin);
$('#signup-button').on('click', signup);
</script>

<!-- /#page-wrapper -->
<?$this->renderScript('common/user-foot.phtml')?>