<?$this->renderScript('common/user-head.phtml')?>
<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Order Detail of SN: <?=htmlspecialchars($this->order->get('sn'))?></h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <dl class="dl-horizontal">
                    <dt>SN</dt>
                    <dd><?=htmlspecialchars($this->order->get('sn'))?></dd>
                    <dt>Status</dt>
                    <dd><?=Model_Order::getStatusDesc($this->order->get('status'))?></dd>

                    <dt></dt><dd>&nbsp;</dd>

                    <dt>City</dt>
                    <dd><?=htmlspecialchars($this->order->get('city'))?></dd>
                    <dt>Passengers</dt>
                    <dd><?=htmlspecialchars($this->order->get('passenger_names'))?></dd>
                    <dt>Passenger Phone</dt>
                    <dd><?=htmlspecialchars($this->order->get('passenger_phone'))?></dd>
                    <dt>Number of Passengers</dt>
                    <dd><?=htmlspecialchars($this->order->get('passenger_num'))?></dd>
                    <dt>Desired Vehicle Type</dt>
                    <dd><?=htmlspecialchars($this->order->get('vehicle'))?></dd>

                    <dt></dt><dd>&nbsp;</dd>

                    <!--
                    <dt>Who</dt>
                    <dd><?=htmlspecialchars($this->order->get('forwho'))?></dd>
                    -->
                    <dt>Ordering Person</dt>
                    <dd><?=htmlspecialchars($this->order->get('contact_name'))?></dd>
                    <dt>Ordering Phone</dt>
                    <dd><?=htmlspecialchars($this->order->get('contact_phone'))?></dd>
                    <dt>Ordering E-Mail</dt>
                    <dd><?=htmlspecialchars($this->order->get('contact_email'))?></dd>

                    <dt></dt><dd>&nbsp;</dd>

                    <dt>When</dt>
                    <dd><?=htmlspecialchars($this->order->get('when'))?></dd>
                    <dt>Pick Up</dt>
                    <dd><?=htmlspecialchars($this->order->get('pickup_address'))?></dd>
                    <?
                    $vias = $this->order->get('via');
                    $vias = json_decode($vias);
                    foreach ($vias as $n=>$via) {
                    ?>
                    <dt>Via #<?=$n+1?></dt>
                    <dd><?=htmlspecialchars($via)?></dd>
                    <?
                    } // foreach $vias as $via
                    ?>
                    <dt>Drop Off</dt>
                    <dd><?=htmlspecialchars($this->order->get('dropoff_address'))?></dd>
                    <!--
                    <dt>Vehicle</dt>
                    <dd><?=htmlspecialchars($this->order->get('vehicle'))?></dd>
                    -->

                    <dt></dt><dd>&nbsp;</dd>

                    <dt>Driver</dt>
                    <dd>
                        <?if ($this->driverAssigned) {?>
                            <?=htmlspecialchars($this->driverAssigned->get('name'))?> <?=htmlspecialchars($this->driverAssigned->get('phone'))?>
                        <?} else {?>
                            Unassigned.
                        <?}?>
                    </dd>
                    <dt>Vehicle</dt>
                    <dd>
                        <?if ($this->vehicleAssigned) {?>
                        <?=htmlspecialchars($this->vehicleAssigned->get('lpn'))?> - <?=htmlspecialchars($this->vehicleAssigned->get('color'))?> <?=htmlspecialchars($this->vehicleAssigned->get('model'))?>, <?=htmlspecialchars($this->vehicleAssigned->get('seats'))?> seats
                        <?} else {?>
                            Unassigned.
                        <?}?>
                    </dd>

                    <dt></dt><dd>&nbsp;</dd>

                    <dt>Payment Method</dt>
                    <dd><?=htmlspecialchars(ucfirst($this->order->get('payment_method')))?></dd>
                    <dt>Notes</dt>
                    <dd><?=nl2br(htmlspecialchars($this->order->get('notes')))?></dd>
                </dl>
                <button class="btn btn-primary" data-toggle="modal" data-target="#edit-modal">Edit this order</button>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <!-- Edit order modal -->
        <div class="modal fade" id="edit-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <form role="form" method="post" action="" id="booking-form">
                        <input type="hidden" name="sn" value="<?=htmlspecialchars($this->order->get('sn'))?>" />
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title" id="myModalLabel">Edit Order (SN: <?=htmlspecialchars($this->order->get('sn'))?>)</h4>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <label for="contact-name">Ordering Person</label>
                                <input id="contact-name" name="contact-name" placeholder="Ordering person full name" class="form-control" required="" type="text" value="<?=htmlspecialchars($this->order->get('contact_name'))?>">
                                <p class="help-block">Title included, eg. Mr Lee</p>
                            </div>
                            <div class="form-group">
                                <label for="contact-phone">Ordering Phone</label>
                                <input id="contact-phone" name="contact-phone" placeholder="Cell phone number of Contact" class="form-control" required="" type="text" value="<?=htmlspecialchars($this->order->get('contact_phone'))?>">
                                <p class="help-block">Country code included, eg. +01(853)555-5555</p>
                            </div>
                            <div class="form-group">
                                <label for="contact-email">Ordering Email</label>
                                <input id="contact-email" name="contact-email" placeholder="E-mail of Contact" class="form-control" required="" type="text" value="<?=htmlspecialchars($this->order->get('contact_email'))?>">
                            </div>
                            <div class="form-group">
                                <label for="passenger-num">Number of Passengers</label>
                                <input id="passenger-num" name="passenger-num" placeholder="Adults, kids, aged" class="form-control" required="" type="text" value="<?=htmlspecialchars($this->order->get('passenger_num'))?>">
                            </div>
                            <div class="form-group">
                                <label for="passenger-names">Passenger Name(s)</label>
                                <input id="passenger-names" name="passenger-names" placeholder="Passenger names and meeting sign" class="form-control" required="" type="text" value="<?=htmlspecialchars($this->order->get('passenger_names'))?>">
                            </div>
                            <div class="form-group">
                                <label for="passenger-phone">Passenger Phone</label>
                                <input id="passenger-phone" name="passenger-phone" placeholder="Passenger phone" class="form-control" required="" type="text" value="<?=htmlspecialchars($this->order->get('passenger_phone'))?>">
                            </div>
                            <div class="form-group">
                                <label for="when">When</label>
                                <input id="when" name="when" placeholder="Date and time" class="form-control" required="" type="text" value="<?=htmlspecialchars($this->order->get('when'))?>">
                                <p class="help-block">Enter the time of pickup in Beijing time(UTC+8), format is year-month-day hour:minute, eg: <i>2015-01-27 20:45</i> for <i>8:45pm 27th Jan 2015</i>.</p>
                            </div>
                            <div class="form-group">
                                <label for="city">City</label>
                                <input id="city" name="city" placeholder="City" class="form-control" required="" type="text" value="<?=htmlspecialchars($this->order->get('city'))?>">
                            </div>
                            <div class="form-group">
                                <label for="pickup-address">Pick Up</label>
                                <input id="pickup-address" name="pickup-address" placeholder="Pick up address" class="form-control" required="" type="text" value="<?=htmlspecialchars($this->order->get('pickup_address'))?>">
                                <p class="help-block">The more detailed the better.</p>
                            </div>
                            <p id="add-via"><a href="javascript:addVia();" class="">Add Via...</a></p>
                            <p class="help-block">(If you want to remove a stop, just simply leave that empty.)</p>
                            <div class="form-group hidden" id="via-group">
                                <input id="via-address" name="via-address[]" placeholder="Via address" class="form-control" required="" type="text">
                            </div>
                            <?
                            $vias = $this->order->get('via');
                            $vias = json_decode($vias);
                            foreach ($vias as $n=>$via) {
                                $n++;
                            ?>
                            <div class="form-group" id="via-group">
                                <input id="via-address-<?=$n?>" name="via-address[]" placeholder="Via address" class="form-control" required="" type="text" value="<?=htmlspecialchars($via)?>">
                            </div>
                            <?
                            } // foreach $vias as $via
                            ?>
                            <div class="form-group">
                                <label for="dropoff-address">Drop Off</label>
                                <input id="dropoff-address" name="dropoff-address" placeholder="Drop off address" class="form-control" required="" type="text" value="<?=htmlspecialchars($this->order->get('dropoff_address'))?>">
                                <p class="help-block">The more detailed the better.</p>
                            </div>
                            <label>Vehicle Type</label>
                            <div class="form-group">
                                <select name="vehicle" class="form-control">
                                    <option value="">Please select a vehicle type</option>
                                    <?foreach ($this->vehicleTypes as $t) {?>
                                    <option value="<?=htmlspecialchars($t['name'])?>" <?if ($t['name']==$this->order->get('vehicle')) {echo 'selected="selected"';}?>><?=htmlspecialchars($t['name'])?></option>
                                    <?}?>
                                </select>
                                <p class="help-block">Choose a desired vehicle type</p>
                            </div>
                            <label>Payment Method</label>
                            <div class="form-group">
                                <label class="radio-inline"><input <?if ($this->order->get('payment_method')=='paypal') {echo 'checked="checked"';}?> type="radio" id="payment-paypal" name="payment-method" value="paypal"> PayPal</label>
                                <label class="radio-inline"><input <?if ($this->order->get('payment_method')=='cash') {echo 'checked="checked"';}?> type="radio" id="payment-cash" name="payment-method" value="cash"> Cash</label>
                                <label class="radio-inline"><input <?if ($this->order->get('payment_method')=='account') {echo 'checked="checked"';}?> type="radio" id="payment-account" name="payment-method" value="account"> Account</label>
                            </div>
                            <div class="form-group">
                                <label for="notes">Notes</label>
                                <textarea id="notes" name="notes" placeholder="Notes" class="form-control" required=""><?=htmlspecialchars($this->order->get('notes'))?></textarea>
                                <p class="help-block">Additional information, such as child seats, luggage, flight number, or to specify a more specific or iconic pickup locations</p>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                            <button type="button" class="btn btn-primary" id="booking-button">Save Change</button>
                        </div>
                    </form>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
        <!-- /.modal -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->
<script>
$('#when').datetimepicker({
    format: 'Y-m-d H:i',
    step: 10,
    minDate: 0,
});

function addVia() {
    var element = $('#via-group').clone();
    $('#add-via').before(element);
    element.removeClass('hidden');
    element.attr('id', '');
}

function submitBookingForm() {
    var options = {
        url: '/private-car/order-detail',
        dataType: 'json',
        beforeSubmit: disableBookingButton,
        success: bookingDidComplate,
        error: bookingDidComplateWithError
    };
    $('#booking-form').ajaxSubmit(options);
}

function bookingDidComplate(data, status, xhr, element) {
    if (data['status'] == 0) {
        alert('Error while processing request, please try again.');
        enableBookingButton();
        return;
    }
    var sn = data['message'];
    window.location.reload();
}

function bookingDidComplateWithError(e) {
    alert('Error while processing request, please try again. ' + e);
    enableBookingButton();
}

function disableBookingButton() {
    $('booking-button').attr('disabled', 'disabled');
}
function enableBookingButton() {
    $('booking-button').removeAttr('disabled');
}
$('#booking-button').on('click', submitBookingForm);
</script>
<?$this->renderScript('common/user-foot.phtml')?>