<?$this->renderScript('common/user-head.phtml')?>
<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">My Orders</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>SN</th>
                                <th>Date</th>
                                <th>Passengers</th>
                                <th>Pick Up</th>
                                <th>Drop Off</th>
                                <th>Status</th>
                                <th>&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?foreach ($this->orders as $order) {?>
                            <tr>
                                <td><?=htmlspecialchars($order['sn'])?></td>
                                <td><?=htmlspecialchars($order['when'])?></td>
                                <td><?=htmlspecialchars($order['passenger_num'])?></td>
                                <td><?=htmlspecialchars($order['pickup_address'])?></td>
                                <td><?=htmlspecialchars($order['dropoff_address'])?></td>
                                <td><?=Model_Order::getStatusDesc($order['status'])?></td>
                                <td><a href="order-detail?sn=<?=$order['sn']?>">Detail</a></td>
                            </tr>
                            <?}?>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->
<?$this->renderScript('common/user-foot.phtml')?>