<?$this->renderScript('common/admin-head.phtml')?>
<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <h1>Add Driver</h1>
        <div class="row">
            <div class="col-lg-12">
                <form class="form-inline" role="form" method="post" action="edit-driver">
                    <div class="form-group">
                        <input type="text" class="form-control" name="name" placeholder="姓名">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="phone" placeholder="手机号">
                    </div>
                    <button type="submit" class="btn btn-primary">Add Driver</button>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Drivers</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>识别码/验证码</th>
                                <th>姓名</th>
                                <th>手机号</th>
                                <th>&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?foreach ($this->drivers as $v) {?>
                            <tr id="driver-<?=$v['code']?>">
                                <td name="code"><?=$v['code']?> / <?=$v['code_verify']?></td>
                                <td name="name"><?=htmlspecialchars($v['name'])?></td>
                                <td name="phone"><?=htmlspecialchars($v['phone'])?></td>
                                <td><a href="javascript:editDriver('<?=$v['code']?>');">Edit</a> <a href="javascript:deleteDriver('<?=$v['code']?>');">Delete</a></td>
                            </tr>
                            <?}?>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <!-- Edit order modal -->
        <div class="modal fade" id="edit-driver" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <form role="form" method="post" action="edit-driver" id="edit-form">
                        <input type="hidden" id="code" name="code" value="" />
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title" id="editModalLabel">Edit Driver</h4>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <label for="name">姓名</label>
                                <input id="name" name="name" placeholder="姓名" class="form-control" required="" type="text" value="">
                            </div>
                            <div class="form-group">
                                <label for="phone">手机号</label>
                                <input id="phone" name="phone" placeholder="手机号" class="form-control" required="" type="text" value="">
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-primary" id="submit-button">Save Change</button>
                        </div>
                    </form>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
        <!-- /.modal -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->
<script>
function editDriver(code) {
    $('#code').val(code);
    var fields = ['name', 'phone'];
    for (var i=0; i<fields.length; i++) {
        var orig = $('#driver-' + code + '>td[name=' + fields[i] + ']').html();
        $('#' + fields[i]).val(orig);
    }
    $('#edit-driver').modal();
}
function deleteDriver(code) {
    if (confirm('Do you want to delete this driver?')) {
        window.location.href="delete-driver?code=" + code;
    }
}
</script>
<?$this->renderScript('common/user-foot.phtml')?>