<?$this->renderScript('common/admin-head.phtml')?>
<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <h3>Log into management panel</h3>
            <form role="form" id="signin-form" method="post" action="">
                 <div class="form-group"><input name="name" placeholder="Username" class="form-control" type="text"></div>
                 <div class="form-group"><input name="password" placeholder="Password" class="form-control" type="password"></div>
                 <div class="form-group"><button id="signin-button" type="submit" class="btn btn-primary btn-lg">Login</button></div>
            </form>
        </div>
    </div>
    <!-- /.container-fluid -->
</div>

<!-- /#page-wrapper -->
<?$this->renderScript('common/user-foot.phtml')?>