<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Management panel</title>

    <!-- Bootstrap Core CSS -->
    <link href="http://apps.bdimg.com/libs/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="/static/css/plugins/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/css/sb-admin-2.css" rel="stylesheet">

    <!-- Common CSS -->
    <link href="/static/css/common.css" rel="stylesheet">

    <link href="/static/css/jquery.datetimepicker.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="http://apps.bdimg.com/libs/fontawesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">

     <!-- jQuery -->
    <script src="http://apps.bdimg.com/libs/jquery/2.1.1/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="http://apps.bdimg.com/libs/bootstrap/3.2.0/js/bootstrap.min.js"></script>

    <!-- Ajax Form -->
    <script src="http://cdn.staticfile.org/jquery.form/3.51/jquery.form.min.js"></script>
    <!-- jQuery Form -->
    <script src="http://apps.bdimg.com/libs/jqueryui/1.9.2/jquery-ui.min.js"></script>

    <script src="/static/js/jquery.datetimepicker.js"></script>

    <script src="http://cdn.staticfile.org/jquery-form-validator/2.1.47/jquery.form-validator.min.js"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/private-car-management/">Robert Car Rental Management Panel</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li><a href="/private-car-management/logout"><i class="fa fa-sign-out fa-fw"></i> Logout</a></li>
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <!--
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </li>
                        -->
                        <!--
                        <li>
                            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Charts<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="flot.html">Flot Charts</a>
                                </li>
                                <li>
                                    <a href="morris.html">Morris.js Charts</a>
                                </li>
                            </ul>
                        </li>
                        -->
                        <li>
                            <a href="/private-car-management/orders" <?if($this->activeMenu=='orders'){echo 'class="active"';}?>><i class="fa fa-bars fa-fw"></i> Orders</a>
                        </li>
                        <li>
                            <a href="/private-car-management/drivers" <?if($this->activeMenu=='drivers'){echo 'class="active"';}?>><i class="fa fa-male fa-fw"></i> Drivers</a>
                        </li>
                        <li>
                            <a href="/private-car-management/vehicles" <?if($this->activeMenu=='vehicles'){echo 'class="active"';}?>><i class="fa fa-car fa-fw"></i> Vehicles</a>
                        </li>
                        <li>
                            <a href="/private-car-management/vehicle-types" <?if($this->activeMenu=='vehicle-types'){echo 'class="active"';}?>><i class="fa fa-car fa-fw"></i> Vehicle Types</a>
                        </li>
                        <li>
                            <a href="/private-car-management/common-phrases" <?if($this->activeMenu=='common-phrases'){echo 'class="active"';}?>><i class="fa fa-flag fa-fw"></i> Common Phrases</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>