<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="/static/css/main.css" type="text/css">
<title>Error</title>
<style type="text/css">
body{ position: relative; height:100%; width:100%; margin: 0; padding: 0; }
#error{ position: absolute; width:500px; top:50% ; left: 50%; margin-top: -150px; margin-left: -250px;}
</style>
</head>
<body>
<div id="error">
<h3>Error occured</h3>
<p><?=$this->msg?></p>
<p><a href="javascript:window.history.back();">Back</a></p>
</div>
</body>
</html>