<!DOCTYPE HTML>
<html lang="zh-CN">
<head>
	<meta charset="UTF-8">
	<title>Error 404 - Page not found</title>
</head>
<body>
	<h1>Page not found. (Error 404)</h1>
	<p>The page you request doesn't exists.</p>
<?php if (IN_CLI || SHOW_ERROR) {?>
<div style="font-family:menlo;courier-new;font-size:12px;">
<h3><?=$this->e->getMessage()?> (<?=$this->e->getFile()?> line <?=$this->e->getLine()?>)</h3>
<pre style="font-family:menlo;courier-new;font-size:12px;">
	<?print_r($this->e->getTrace())?>
</pre>
</div>
<?}?>
</body>
</html>