<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="/static/css/main.css" type="text/css" />
<title>Message</title>
<style type="text/css">
body{ position: relative; height:100%; width:100%; margin: 0; padding: 0; }
#msg{ position: absolute; width:500px; top:50% ; left: 50%; margin-top: -150px; margin-left: -250px;}
</style>
</head>

<body>
<div id="msg">
<h3>Message</h3>
<p> <?=$this->msg?> </p>
<p><a href="javascript:window.history.back();">Back</a></p>
</div>
</body>
</html>
