<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="/static/css/main.css" type="text/css">
<meta http-equiv="refresh" content="<?=isset($this->waitTime) ? $this->waitTime : '3' ?>; url=<?=$this->link?>" />

<title><?=strip_tags($this->msg) ?></title>

<style type="text/css">
body{ position: relative; height:100%; width:100%; margin: 0; padding: 0; }
#msg{ position: absolute; width:500px; top:50% ; left: 50%; margin-top: -150px; margin-left: -250px;}
</style>
</head>

<body>

  <div id="msg">
  <h3>Message:</h3>
 	<p><?=$this->msg ?></p>
	<p><a href="<?=$this->link ?>">Click here if your browser doesn't redirect automatically...</a></p>
	</div>

</body>
</html>